# Generated by Django 4.2.1 on 2023-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_cases_classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcourtcase',
            name='crime',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadcourtcase',
            name='sentence',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
