# Generated by Django 3.2.4 on 2023-06-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_range', models.CharField(max_length=10)),
                ('excel_file', models.FileField(upload_to='data_files')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
